### ISSUE TITLE
Cannot compile on Windows

### ISSUE THREAD

**Issue by observant2** [dpogretskiy/specs-ggez-showcase#1]
I get
```
error: failed to run custom build command for `special v0.1.0 (file:///C:/Users/******/Documents/Code/Rust/specs-ggez-showcase)`
process didn't exit successfully: `C:\Users\******\Documents\Code\Rust\specs-ggez-showcase\target\debug\build\special-20fd59dfe3a99139\build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=all=C:\Users\*****\Documents\Code\Rust\specs-ggez-showcase\msvc\lib\64

--- stderr
thread 'main' panicked at 'Can't read DLL dir: Os { code: 3, kind: NotFound, message: "Das System kann den angegebenen Pfad nicht finden." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
The german error message says that the specified path can't be found.

I use rust nightly 1.26.0, but it shouldn't have something to do with it. It looks for a "msvc" path inside the project root. That seems wrong. 😄 

As a side note: Never ever use `*` for a version in your cargo.toml. Always pin it down to a specific version. Otherwise if a library upgrades to a new major version(!) your project will most likely not compile.

**Comment by dpogretskiy** [comment]
I have Cargo.lock in repo, so it should use pretty specific versions during compilation, but i see what happens, it looks for SDL.dll inside project folder, it happens directly in build.rs file, somehow msvc directory is not in the repo. I should be able to fix this.

**Comment by dpogretskiy** [comment]
Check if it will compile now, it should.

**Comment by observant2** [comment]
Very nice! It works! Thank you!

Ah! I didn't see the `.lock` file. I had bad experiences in the past with projects (also in the npm ecosystem) specifying wildcards for versions. Many broken projects. As long as you commit the `.lock` file there should be no problem. 🙂

**Comment by dpogretskiy** [comment]
Yeah, cargo is cool, it's an unspoken (actually spoken) rule to commit .lock file with binary projects, and not commit it with library projects.
